### ISSUE TITLE
Got assertion error on my files

### ISSUE THREAD

**Issue by SvenEwald** [validator/maven-plugin#3]
Exception in thread "main" java.lang.AssertionError: strBufLen not reset after previous use!
	at nu.validator.htmlparser.impl.Tokenizer.clearStrBufBeforeUse(Tokenizer.java:940)
	at nu.validator.htmlparser.impl.Tokenizer.stateLoop(Tokenizer.java:3847)
	at nu.validator.htmlparser.impl.Tokenizer.tokenizeBuffer(Tokenizer.java:1429)
	at nu.validator.htmlparser.io.Driver.runStates(Driver.java:320)
	at nu.validator.htmlparser.io.Driver.tokenize(Driver.java:219)
	at nu.validator.htmlparser.sax.HtmlParser.tokenize(HtmlParser.java:488)
	at nu.validator.htmlparser.sax.HtmlParser.parse(HtmlParser.java:408)
	at nu.validator.xml.WiretapXMLReaderWrapper.parse(WiretapXMLReaderWrapper.java:158)
	at nu.validator.validation.SimpleDocumentValidator.checkAsHTML(SimpleDocumentValidator.java:532)
	at nu.validator.validation.SimpleDocumentValidator.checkHtmlFile(SimpleDocumentValidator.java:451)
	at nu.validator.maven.plugin.NVUValidator.checkHtmlFile(NVUValidator.java:260)
	at nu.validator.maven.plugin.NVUValidator.checkFile(NVUValidator.java:224)
	at nu.validator.maven.plugin.NVUValidator.validateFileset(NVUValidator.java:132)
	at nu.validator.maven.plugin.NVUValidator.validate(NVUValidator.java:96)
	at nu.validator.maven.plugin.NVUValidatorMojo.execute(NVUValidatorMojo.java:91)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

**Comment by McNetic** [comment]
Sorry for not reacting earlier - I did not receive a notification for this issue. Can you provide a minimal example to reproduce the issue?

**Comment by SvenEwald** [comment]
All fine :) Just add -ea to JRE options.

**Comment by McNetic** [comment]
Ok then.
